name: project
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_otp_text_field: ^1.1.0+2
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  liquid_swipe: ^3.0.0
  firebase_core: ^2.15.1
  firebase_auth: ^4.9.0
  firebase_storage: ^11.2.6
  cloud_firestore: ^4.9.1
  fluttertoast: ^8.2.2
  email_auth: ^1.0.0
  otp_text_field: ^1.1.3
  animated_text_kit: ^4.2.2
  google_nav_bar: ^5.0.6
  carousel_slider: ^4.2.1
  smooth_page_indicator: ^1.1.0
  dots_indicator: ^3.0.0 
  flutter_svg: ^2.0.7
  google_fonts: ^6.1.0
  flutter_spinkit: ^5.1.0
  provider: ^6.0.5
  google_sign_in: ^6.1.5
  timeago: ^3.5.0
  intl: ^0.18.1
  image_picker: ^1.0.4
  image_cropper: ^5.0.0
  path: ^1.8.3
  uuid: ^3.0.7
  flutter_image_slider: ^0.0.2
  geolocator: ^10.1.0
  geocoding: ^2.1.0
  url_launcher: ^6.1.14
  map_launcher: ^2.5.0+1
  path_provider: ^2.1.1
  http: ^1.1.0
  xml: ^6.3.0
  flutter_html: ^3.0.0-beta.2
  html: ^0.15.4
  selectable: ^0.3.0
  firebase_messaging: ^14.6.9
  flutter_local_notifications: ^16.1.0
  app_settings: ^5.1.1
  flutter_rating_bar: ^4.0.1
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons: 
  android: true
  image_path: "img/ss.png"

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - img/
    - assets/images/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
